- src/main/webapp/WEB-INF/views/daminoUserView/main.jsp
> 메인 페이지 css경로 수정

- src/main/webapp/resources/css/user/common.css
> ../../images/user/sp_common.png 로 css 변경

- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/quickOrder_defaultSetting.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/quickOrdermain.jsp
> quickorder 수정 및 quickOrder_defaultSetting.jsp 업로드

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page2.jsp
> order_page2 추가

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page2.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page3.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_status_cook.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_status_delivery.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/quickOrder_defaultSetting.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/quickOrdermain.jsp
> order 및 quickorder 전체수정

- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/change_info.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/sign_up_1.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/user_info_confirm.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/withdrawal.jsp
> userinfo폴더 jsp수정

- src/main/java/com/damino/web/test/ViewTestController.java
public ModelAndView getAdminMainPage() {
> no message

- src/main/java/com/damino/web/test/ViewTestController.java
> Controller - banner 폴더 경로 변경

- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_empty.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/faq_homePage.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/faq_howToOrder.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/faq_main.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/faq_orderCheck.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/faq_sendPresent.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/faq_wrapOrder.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/noticeList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/qnaForm.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/company/ceo.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/company/chainstore1.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/company/chainstore2.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/company/chainstore3.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/company/chainstore4.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/company/international.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/company/location.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/company/overview.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/ecoupon/ecouponInput.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/ecoupon/ecouponResult.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/change_info.jsp
> css, js 파일 경로 수정

- src/main/webapp/WEB-INF/views/daminoManagerView/error/error_401.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/error/error_404.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/error/error_500.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/main.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/members/NewFile.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/order/NewFile.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/statistics/NewFile.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/store/NewFile.jsp
> daminoManagerView 폴더구조 세팅

- src/main/java/com/damino/web/test/ViewTestController.java
controller s 수정
mav.setViewName("/members/member/memberEdit"); |  
-- | --
mav.setViewName("/members/member/memberInfo"); |  
> controller s 수정

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/webapp/WEB-INF/views/daminoUserView/order/groupOrder.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_status_deliveryDone.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_status_receive.jsp
>  Order에 추가 viewtestcontroller 추가

- src/main/webapp/WEB-INF/views/daminoUserView/order/groupOrder.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_status_deliveryDone.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_status_receive.jsp
> user/ 빠진 부분 추가

- src/main/webapp/WEB-INF/views/daminoAdminView/sites/banner/bannerBoardEdit.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/banner/bannerBoardView.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/questionAndAnswer/qna_insert.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/questionAndAnswer/qna_list.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/terms/terms_insert.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/terms/terms_list.jsp
> 홈페이지 관리자 페이지 사이드메뉴바 링크 수정

- src/main/webapp/WEB-INF/views/daminoAdminView/sites/questionAndAnswer/qna_list.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/terms/terms_list.jsp
terms_list.jsp, qna_list.jsp 경로 수정 (버튼 링크부분)
> terms_list.jsp, qna_list.jsp 경로 수정 (버튼 링크부분)

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/webapp/WEB-INF/views/daminoManagerView/error/error_401.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/error/error_500.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/main.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/members/managerLogin.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/members/managerRegister.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/members/passwordChange.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/order/orderList.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/order/orderSearch.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/store/storeManagerInfo.jsp
1. controller - 매장관리자, 홈페이지관리자, 사용자페이지(userInfo 삭제)
2. 매장관리자페이지 경로 추가
> 1. controller - 매장관리자, 홈페이지관리자, 사용자페이지(userInfo 삭제)

- src/main/java/com/damino/web/test/ViewTestController.java
controller - memberEdit 부분 오탈자 수정
> controller - memberEdit 부분 오탈자 수정

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail001pp.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/login/login.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myCoupon.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myLevel.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myOrderList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myOrderList_cancle.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myQuestionList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myUserInfoConfirm.jsp
> login , mypage, goods

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail001pp.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/login/login.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myCoupon.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myLevel.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myOrderList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myOrderList_cancle.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myQuestionList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myUserInfoConfirm.jsp
goods, login, mypage 폴더 <a> 태그 경로 수정
> goods, login, mypage 폴더 <a> 태그 경로 수정

- src/main/java/com/damino/web/test/OshService.java
- src/main/java/com/damino/web/test/OshServiceClient.java
- src/main/java/com/damino/web/test/OshServiceImpl.java
- src/main/java/com/damino/web/test/OshTestDAO.java
- src/main/java/com/damino/web/test/OshTestVO.java
- src/main/resources/applicationContext.xml
- src/main/resources/mappings/osh-mapping.xml
- src/main/resources/mybatis-config.xml
> DB 연동 Test 예시

- src/main/webapp/WEB-INF/views/daminoAdminView/board/boardList.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/board/boardView.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/board/boardWrite.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/members/market/marketList.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/members/member/memberInfo.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/insertMenu_drink.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/insertMenu_pizza.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/insertMenu_side.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/insertMenu_topping.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/menuInfo.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/menuList.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/noticeBoard/noticeBoardEdit.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/noticeBoard/noticeBoardView.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/banner/bannerBoardEdit.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/banner/bannerBoardView.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/questionAndAnswer/qna_insert.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/questionAndAnswer/qna_list.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/terms/terms_insert.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/terms/terms_list.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/store/storeView.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/store_sales/salesStatus.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/order/orderList.jsp
홈페이지 관리자, 매장 관리자 페이지 새로고침 버튼 이미지 경로 수정
> 홈페이지 관리자, 매장 관리자 페이지 새로고침 버튼 이미지 경로 수정

- src/main/webapp/WEB-INF/views/daminoAdminView/members/member/login.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/members/member/regForm.jsp
> login.jsp , regForm.jsp 수정

- src/main/java/com/damino/web/admin/example/ExampleController.java
- src/main/java/com/damino/web/admin/example/ExampleDAO.java
- src/main/java/com/damino/web/admin/example/ExampleService.java
- src/main/java/com/damino/web/admin/example/ExampleVO.java
- src/main/java/com/damino/web/admin/example/impl/ExampleDAOimpl.java
- src/main/java/com/damino/web/admin/example/impl/ExampleServiceImpl.java
- src/main/java/com/damino/web/store/example/impl/ExampleDAOimpl.java
- src/main/java/com/damino/web/store/example/impl/ExampleServiceImpl.java
- src/main/java/com/damino/web/store/examplee/ExampleController.java
- src/main/java/com/damino/web/store/examplee/ExampleDAO.java
- src/main/java/com/damino/web/store/examplee/ExampleService.java
- src/main/java/com/damino/web/store/examplee/ExampleVO.java
- src/main/java/com/damino/web/user/example/ExampleController.java
- src/main/java/com/damino/web/user/example/ExampleDAO.java
- src/main/java/com/damino/web/user/example/ExampleService.java
- src/main/java/com/damino/web/user/example/ExampleVO.java
- src/main/java/com/damino/web/user/example/impl/ExampleDAOimpl.java
- src/main/java/com/damino/web/user/example/impl/ExampleServiceImpl.java
> Java 패키지 구조 예시

- src/main/java/com/damino/web/store/example/ExampleController.java
- src/main/java/com/damino/web/store/example/ExampleDAO.java
- src/main/java/com/damino/web/store/example/ExampleService.java
- src/main/java/com/damino/web/store/example/ExampleVO.java
- src/main/java/com/damino/web/store/example/impl/ExampleDAOimpl.java
- src/main/java/com/damino/web/store/example/impl/ExampleServiceImpl.java
- src/main/java/com/damino/web/store/examplee/ExampleController.java
- src/main/java/com/damino/web/store/examplee/ExampleDAO.java
- src/main/java/com/damino/web/store/examplee/ExampleService.java
- src/main/java/com/damino/web/store/examplee/ExampleVO.java
> 패키지 오타 수정..

- src/main/webapp/WEB-INF/spring/daminoAdminContext/daminoAdmin-context.xml
- src/main/webapp/WEB-INF/spring/daminoManagerContext/daminoManager-context.xml
- src/main/webapp/WEB-INF/spring/daminoUserContext/daminoUser-context.xml
> component-scan 패키지 경로 수정

- src/main/java/com/damino/web/user/example/ExampleController.java
- src/main/java/com/damino/web/user/example/ExampleDAO.java
- src/main/java/com/damino/web/user/example/ExampleService.java
- src/main/java/com/damino/web/user/example/ExampleVO.java
- src/main/java/com/damino/web/user/example/impl/ExampleDAOimpl.java
- src/main/java/com/damino/web/user/example/impl/ExampleServiceImpl.java
- src/main/java/com/damino/web/user/login/LoginController.java
- src/main/java/com/damino/web/user/login/LoginService.java
- src/main/java/com/damino/web/user/login/UserDAO.java
- src/main/java/com/damino/web/user/login/UserVO.java
- src/main/java/com/damino/web/user/login/impl/LoginServiceImpl.java
- src/main/java/com/damino/web/user/login/impl/UserDAOimpl.java
- src/main/webapp/WEB-INF/spring/daminoAdminContext/daminoAdmin-context.xml
- src/main/webapp/WEB-INF/spring/daminoManagerContext/daminoManager-context.xml
- src/main/webapp/WEB-INF/spring/daminoUserContext/daminoUser-context.xml
- src/main/webapp/WEB-INF/views/daminoUserView/login/login.jsp
> 로그인 테스트 기본 틀 작성

- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myQuestionList.jsp
- src/main/webapp/resources/css/user/common.css
> 1:1 문의사항 팝업창 위치 변경

- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
- src/main/webapp/resources/js/user/member.js
member.js 추가, 사용자 회원가입 입력 폼 수정
> member.js 추가, 사용자 회원가입 입력 폼 수정

- pom.xml
> CoolSMS API Dependency 추가

- src/main/java/com/damino/web/user/board/impl/QnaBoardDAOImpl.java
- src/main/java/com/damino/web/user/board/impl/QnaBoardServiceImpl.java
- src/main/java/com/damino/web/user/join/JoinController.java
- src/main/java/com/damino/web/user/join/JoinService.java
- src/main/java/com/damino/web/user/join/impl/JoinServiceImpl.java
- src/main/java/com/damino/web/util/AuthKeySend.java
- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
QnaBoard 패키지 수정, user.join 패키지 추가
> QnaBoard 패키지 수정, user.join 패키지 추가

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/webapp/WEB-INF/views/daminoAdminView/board/boardList.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/board/boardView.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/noticeDetail.jsp
사용자 공지사항 상세보기 추가
noticeDetail.jsp 추가
ViewTestController에도 추가
> 사용자 공지사항 상세보기 추가

- pom.xml
- src/main/java/com/damino/web/user/join/JoinController.java
- src/main/java/com/damino/web/user/join/impl/JoinServiceImpl.java
- src/main/resources/applicationContext.xml
- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
> 사용자페이지 회원가입 인증문자 발송 구현

- src/main/resources/mappings/board-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myQuestion_view.jsp
> board-mapping 1:1 문의사항 내용 추가

- src/main/java/com/damino/web/admin/example/ExampleController.java
- src/main/java/com/damino/web/admin/example/ExampleDAO.java
- src/main/java/com/damino/web/admin/example/ExampleService.java
- src/main/java/com/damino/web/admin/example/ExampleVO.java
- src/main/java/com/damino/web/admin/example/impl/ExampleDAOimpl.java
- src/main/java/com/damino/web/admin/example/impl/ExampleServiceImpl.java
- src/main/java/com/damino/web/store/example/ExampleController.java
- src/main/java/com/damino/web/store/example/ExampleDAO.java
- src/main/java/com/damino/web/store/example/ExampleService.java
- src/main/java/com/damino/web/store/example/ExampleVO.java
- src/main/java/com/damino/web/store/example/impl/ExampleDAOimpl.java
- src/main/java/com/damino/web/store/example/impl/ExampleServiceImpl.java
- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/board/NoticeBoardController.java
- src/main/java/com/damino/web/user/board/NoticeBoardDAO.java
- src/main/java/com/damino/web/user/board/NoticeBoardService.java
- src/main/java/com/damino/web/user/board/NoticeBoardVO.java
- src/main/java/com/damino/web/user/board/impl/NoticeBoardDAOImpl.java
- src/main/java/com/damino/web/user/board/impl/NoticeBoardServiceImpl.java
- src/main/resources/mappings/board-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/board/noticeList.jsp
사용자 페이지 공지사항 목록 가져오기
noticeList.do
> 사용자 페이지 공지사항 목록 가져오기

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/board/NoticeBoardController.java
- src/main/java/com/damino/web/user/board/NoticeBoardDAO.java
- src/main/java/com/damino/web/user/board/NoticeBoardService.java
- src/main/java/com/damino/web/user/board/impl/NoticeBoardDAOImpl.java
- src/main/java/com/damino/web/user/board/impl/NoticeBoardServiceImpl.java
- src/main/webapp/WEB-INF/views/daminoAdminView/board/boardView.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/noticeDetail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/noticeList.jsp
> 사용자페이지 공지사항 상세보기, ck에디터 추가

- src/main/java/com/damino/web/user/board/QnaBoardController.java
- src/main/java/com/damino/web/user/board/QnaBoardDAO.java
- src/main/java/com/damino/web/user/board/QnaBoardVO.java
- src/main/java/com/damino/web/user/board/impl/QnaBoardDAOImpl.java
- src/main/java/com/damino/web/user/board/impl/QnaBoardServiceImpl.java
- src/main/resources/mappings/board-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myQuestionList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myQuestion_view.jsp
1:1 문의사항 글 목록 조회, 삭제 기능 구현. 글 등록 기능 진행중
- board-mapping.xml 수정, QnaBoard 관련 파일 추가
> 1:1 문의사항 글 목록 조회, 삭제 기능 구현. 글 등록 기능 진행중

- src/main/java/com/damino/web/admin/orderlist/OrderlistController.java
- src/main/java/com/damino/web/admin/orderlist/OrderlistDAO.java
- src/main/java/com/damino/web/admin/orderlist/OrderlistService.java
- src/main/java/com/damino/web/admin/orderlist/OrderlistVO.java
- src/main/java/com/damino/web/admin/orderlist/impl/OrderlistDAOImpl.java
- src/main/java/com/damino/web/admin/orderlist/impl/OrderlistServiceImpl.java
- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/resources/mappings/orderlist-mapping.xml
- src/main/resources/mybatis-config.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/store_sales/orderList.jsp
> 홈페이지 관리자 주문내역 DB 불러오기

- src/main/java/com/damino/web/admin/board/BoardController.java
- src/main/java/com/damino/web/admin/board/BoardVO.java
- src/main/resources/mappings/board-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/board/boardList.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/board/boardWrite.jsp
게시판글 그룹짓는 flag 추가 (공지사항, 보도자료)
> 게시판글 그룹짓는 flag 추가 (공지사항, 보도자료)

- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
사용자 페이지 회원가입폼 regForm.jsp 비밀번호 입력, 비밀번호 확인 입력폼 추가
> 사용자 페이지 회원가입폼 regForm.jsp 비밀번호 입력, 비밀번호 확인 입력폼 추가

- src/main/java/com/damino/web/user/board/NotciePagingVO.java
- src/main/webapp/WEB-INF/views/daminoAdminView/board/boardList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/noticeList.jsp
> 페이징처리 작업 미완성

- pom.xml
- src/main/java/com/damino/web/user/join/JoinController.java
- src/main/resources/spring-security.xml
- src/main/webapp/WEB-INF/web.xml
spring security 의존성 추가, spring-security 설정파일 추가, JoinController 수정
> spring security 의존성 추가, spring-security 설정파일 추가, JoinController 수정

- pom.xml
- src/main/java/com/damino/web/admin/menu/MenuController.java
- src/main/java/com/damino/web/admin/menu/MenuDAO.java
- src/main/java/com/damino/web/admin/menu/MenuService.java
- src/main/java/com/damino/web/admin/menu/PizzaVO.java
- src/main/java/com/damino/web/admin/menu/impl/MenuDAOImpl.java
- src/main/java/com/damino/web/admin/menu/impl/MenuServiceImpl.java
- src/main/resources/applicationContext.xml
- src/main/resources/mappings/menu-mapping.xml
- src/main/resources/mybatis-config.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/insertMenu_pizza.jsp
> 파일업로드 관련 의존성 추가, 메뉴 등록-피자 구현

- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
> 공사중 - regform -

- src/main/java/com/damino/web/admin/menu/DrinkEtcVO.java
- src/main/java/com/damino/web/admin/menu/MenuController.java
- src/main/java/com/damino/web/admin/menu/MenuDAO.java
- src/main/java/com/damino/web/admin/menu/MenuService.java
- src/main/java/com/damino/web/admin/menu/PizzaVO.java
- src/main/java/com/damino/web/admin/menu/SideVO.java
- src/main/java/com/damino/web/admin/menu/ToppingVO.java
- src/main/java/com/damino/web/admin/menu/impl/MenuDAOImpl.java
- src/main/java/com/damino/web/admin/menu/impl/MenuServiceImpl.java
- src/main/resources/mappings/menu-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/insertMenu_drink.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/insertMenu_side.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/insertMenu_topping.jsp
관리자 페이지 메뉴 등록 (피자, 사이드, 음료기타, 토핑) 구현
> 관리자 페이지 메뉴 등록 (피자, 사이드, 음료기타, 토핑) 구현

- src/main/java/com/damino/web/user/board/NoticeBoardController.java
- src/main/java/com/damino/web/user/board/NoticeBoardDAO.java
- src/main/java/com/damino/web/user/board/NoticeBoardService.java
- src/main/java/com/damino/web/user/board/impl/NoticeBoardDAOImpl.java
- src/main/java/com/damino/web/user/board/impl/NoticeBoardServiceImpl.java
- src/main/resources/mappings/board-mapping.xml
> 사용자 페이지 공지사항 게시판 조회수 추가

- src/main/java/com/damino/web/user/board/NoticeBoardController.java
- src/main/java/com/damino/web/user/board/NoticeBoardDAO.java
- src/main/java/com/damino/web/user/board/NoticeBoardService.java
- src/main/java/com/damino/web/user/board/NoticePageMaker.java
- src/main/java/com/damino/web/user/board/NoticePagingVO.java
- src/main/java/com/damino/web/user/board/impl/NoticeBoardDAOImpl.java
- src/main/java/com/damino/web/user/board/impl/NoticeBoardServiceImpl.java
- src/main/resources/mappings/board-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/board/noticeList.jsp
> 사용자 페이지 공지사항 게시판 페이징처리 (미완성)

- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
구현 - 아이디중복 사이트 하단창
구현중  - email 중복
> regform 수정중

- src/main/webapp/resources/js/user/member.js
> member.js 수정

- src/main/resources/mappings/board-mapping.xml
> 1:1 문의사항 count 쿼리 수정

- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
> 사용자 회원가입 regForm.jsp 수정

- src/main/java/com/damino/web/user/board/QnaBoardController.java
- src/main/java/com/damino/web/user/board/paging/PageMaker.java
> 1:1 문의게시판 오류 수정

- src/main/resources/mappings/board-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/board/boardView.jsp
> 홈페이지 관리자 공지사항 수정부분

- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
- src/main/webapp/resources/js/user/member.js
regForm.jsp, member.js 유효성 체크 완료, 전체 선택 (불완전) 수정
> regForm.jsp, member.js 유효성 체크 완료, 전체 선택 (불완전) 수정

- src/main/java/com/damino/web/user/login/LoginController.java
- src/main/java/com/damino/web/user/login/LoginService.java
- src/main/java/com/damino/web/user/regist/RegistController.java
- src/main/java/com/damino/web/user/regist/RegistService.java
- src/main/java/com/damino/web/user/regist/UserMemberDAO.java
- src/main/java/com/damino/web/user/regist/impl/RegistServiceImpl.java
- src/main/java/com/damino/web/user/regist/impl/UserMemberDAOimpl.java
- src/main/resources/mappings/usermember-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
<작업중>
주석, hidden, 아이디 중복체크 형식, 아이디 관련 메소드들 usermember로 이사.
> 이메일 중복체크 구현  --1차--

- src/main/java/com/damino/web/admin/faq/FaqService.java
- src/main/java/com/damino/web/admin/faq/FaqVO.java
- src/main/resources/mappings/menu-mapping.xml
menu-mapping.xml 쿼리문 수정, FaqVO, FaqService 추가
> menu-mapping.xml 쿼리문 수정, FaqVO, FaqService 추가

- src/main/java/com/damino/web/user/board/QnaBoardController.java
- src/main/java/com/damino/web/user/board/QnaBoardDAO.java
- src/main/java/com/damino/web/user/board/QnaBoardService.java
- src/main/java/com/damino/web/user/board/impl/QnaBoardDAOImpl.java
- src/main/java/com/damino/web/user/board/impl/QnaBoardServiceImpl.java
- src/main/java/com/damino/web/user/board/paging/Paging_adm.java
- src/main/resources/mappings/board-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/userQnaBoard/myQuestionList_adm.jsp
1. 1:1 문의사항 어드민 권한 페이지 생성 (select : 전체 글 조회 상태)
2. 처리대기 조회 버튼 및 처리대기 상태 조회 기능 구현
> 1:1 문의사항 어드민 권한 페이지 생성 (select : 전체 글 조회 상태) 외 1개 기능

- src/main/java/com/damino/web/admin/board/BoardController.java
- src/main/webapp/WEB-INF/views/daminoUserView/board/noticeList.jsp
> BoardController무한 insert 주석

- src/main/java/com/damino/web/admin/homepage/user/UsersController.java
- src/main/java/com/damino/web/admin/homepage/user/UsersDAO.java
- src/main/java/com/damino/web/admin/homepage/user/UsersService.java
- src/main/java/com/damino/web/admin/homepage/user/UsersVO.java
- src/main/java/com/damino/web/admin/homepage/user/impl/UsersDAOImpl.java
- src/main/java/com/damino/web/admin/homepage/user/impl/UsersServiceImpl.java
> 패키지명 변경으로 인한 오류 수정

- src/main/java/com/damino/web/admin/homepage/user/impl/UsersServiceImpl.java
- src/main/resources/mappings/seeuser-mapping.xml
패키지명 변경으로 인한 mapping 파일 수정, @repository bean 이름 일치 작업
> 패키지명 변경으로 인한 mapping 파일 수정, @repository bean 이름 일치 작업

- src/main/resources/mybatis-config.xml
market_admin_member-mapping.xml 등록
> market_admin_member-mapping.xml 등록

- src/main/java/com/damino/web/admin/market/member/regist/MarketAdminRegistController.java
- src/main/java/com/damino/web/user/login/LoginController.java
- src/main/webapp/WEB-INF/views/daminoManagerView/members/managerRegister.jsp
1. 사용자페이지 로그인 컨트롤러 주석해제(오류해결)
2. 매장관리자페이지 - 회원가입 관련 value 변경
> 사용자페이지 로그인 컨트롤러 주석해제(오류해결) 외 1건

- src/main/java/com/damino/web/admin/faq/FaqController.java
- src/main/java/com/damino/web/admin/faq/FaqDAO.java
- src/main/java/com/damino/web/admin/faq/FaqVO.java
- src/main/java/com/damino/web/admin/faq/impl/FaqDAOImpl.java
- src/main/java/com/damino/web/admin/faq/impl/FaqServiceImpl.java
- src/main/java/com/damino/web/admin/homepage/member/HomepageAdminMemVO.java
- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/resources/mappings/faq-mapping.xml
- src/main/resources/mappings/seeuser-mapping.xml
- src/main/resources/mybatis-config.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/questionAndAnswer/qna_list.jsp
자주 묻는 질문 조회기능 추가, ViewTestController 수정
> 자주 묻는 질문 조회기능 추가, ViewTestController 수정

- src/main/java/com/damino/web/admin/market/member/login/MarketAdminLoginController.java
- src/main/java/com/damino/web/admin/market/member/login/MarketAdminLoginService.java
- src/main/java/com/damino/web/admin/market/member/login/impl/MarketAdminLoginServiceImpl.java
- src/main/java/com/damino/web/admin/market/member/regist/MarketAdminRegistController.java
- src/main/java/com/damino/web/admin/market/member/regist/impl/MarketAdminMemberDAOImpl.java
- src/main/resources/mappings/market_admin_member-mapping.xml
- src/main/webapp/WEB-INF/views/daminoManagerView/members/managerRegister.jsp
매장관리자페이지 회원가입 기능 구현 (매장 선택 기능은 추후 DB정보 불러올 예정)
> 매장관리자페이지 회원가입 기능 구현 (매장 선택 기능은 추후 DB정보 불러올 예정)

- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
> 아이디 이메일 hidden

- src/main/java/com/damino/web/admin/faq/FaqController.java
- src/main/java/com/damino/web/admin/faq/FaqDAO.java
- src/main/java/com/damino/web/admin/faq/FaqService.java
- src/main/java/com/damino/web/admin/faq/impl/FaqDAOImpl.java
- src/main/java/com/damino/web/admin/faq/impl/FaqServiceImpl.java
- src/main/java/com/damino/web/user/faq/FaqViewController.java
- src/main/java/com/damino/web/user/faq/FaqViewDAO.java
- src/main/java/com/damino/web/user/faq/FaqViewService.java
- src/main/java/com/damino/web/user/faq/impl/FaqViewDAOImpl.java
- src/main/java/com/damino/web/user/faq/impl/FaqViewServiceImpl.java
- src/main/resources/mappings/faq-mapping.xml
- src/main/resources/mappings/faqview-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/questionAndAnswer/faqType_list.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/questionAndAnswer/qna_list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/faq_homePage.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/faq_howToOrder.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/faq_orderCheck.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/faq_sendPresent.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/board/faq_wrapOrder.jsp
사용자 페이지 FAQ 페이지별 조회, 토글버튼 이벤트 추가
> 사용자 페이지 FAQ 페이지별 조회, 토글버튼 이벤트 추가

- src/main/java/com/damino/web/admin/faq/FaqController.java
- src/main/java/com/damino/web/admin/faq/FaqDAO.java
- src/main/java/com/damino/web/admin/faq/FaqService.java
- src/main/java/com/damino/web/admin/faq/FaqVO.java
- src/main/java/com/damino/web/admin/faq/impl/FaqDAOImpl.java
- src/main/java/com/damino/web/admin/faq/impl/FaqServiceImpl.java
- src/main/resources/mappings/faq-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/questionAndAnswer/qna_list.jsp
홈페이지 관리자 FAQ 리스트 카테고리별 검색 기능 구현
> 홈페이지 관리자 FAQ 리스트 카테고리별 검색 기능 구현

- src/main/java/com/damino/web/admin/market/member/regist/MarketAdminRegistController.java
- src/main/webapp/WEB-INF/views/daminoManagerView/members/managerRegister.jsp
1. defalut 셀렉트박스에 대한 하위 셀렉트박스 추가
2. id 중복체크 버튼 클릭 시 승인신청 버튼 활성화
3. 승인신청 버튼 클릭시 각 항목 공백 및 id 중복체크 실행
> 매장관리자페이지 회원가입 부가기능 추가

- src/main/java/com/damino/web/admin/member/regist/AdminMemberController.java
- src/main/java/com/damino/web/admin/member/regist/AdminMemberDAO.java
- src/main/java/com/damino/web/admin/member/regist/AdminMemberService.java
- src/main/java/com/damino/web/admin/member/regist/impl/AdminMemberDAOImpl.java
- src/main/java/com/damino/web/admin/member/regist/impl/AdminMemberServiceImpl.java
- src/main/resources/mappings/adminmember-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/members/member/regForm.jsp
> 홈페이지관리 - 회원가입

- src/main/java/com/damino/web/admin/faq/FaqController.java
- src/main/java/com/damino/web/user/coupon/CouponController.java
- src/main/java/com/damino/web/user/coupon/CouponDAO.java
- src/main/java/com/damino/web/user/coupon/CouponService.java
- src/main/java/com/damino/web/user/coupon/CouponVO.java
- src/main/java/com/damino/web/user/coupon/impl/CouponDAOImpl.java
- src/main/java/com/damino/web/user/coupon/impl/CouponServiceImpl.java
- src/main/java/com/damino/web/user/login/LoginController.java
- src/main/resources/mappings/usermember-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/main.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myLevel.jsp
사용자페이지 로그아웃 기능, usermember-mapping.xml, mylevel.jsp 수정, Coupon 패키지 구조 작성
> 사용자페이지 로그아웃 기능, usermember-mapping.xml, mylevel.jsp 수정, Coupon 패키지 구조 작성

- src/main/java/com/damino/web/admin/terms/TermsController.java
- src/main/java/com/damino/web/admin/terms/TermsDAO.java
- src/main/java/com/damino/web/admin/terms/TermsService.java
- src/main/java/com/damino/web/admin/terms/TermsVO.java
- src/main/java/com/damino/web/admin/terms/impl/TermsDAOImpl.java
- src/main/java/com/damino/web/admin/terms/impl/TermsServiceImpl.java
- src/main/resources/mappings/terms-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/terms/terms_insert.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/terms/terms_list.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/terms/terms_view.jsp
> 약관 이미지 insert

- src/main/java/com/damino/web/test/ViewTestController.java
> ViewTestController 수정

- src/main/webapp/WEB-INF/web.xml
> 스프링 시큐리티 주석처리 관련 web.xml 수정

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/coupon/CouponController.java
- src/main/java/com/damino/web/user/coupon/CouponDAO.java
- src/main/java/com/damino/web/user/coupon/CouponService.java
- src/main/java/com/damino/web/user/coupon/impl/CouponDAOImpl.java
- src/main/java/com/damino/web/user/coupon/impl/CouponServiceImpl.java
- src/main/java/com/damino/web/user/login/LoginController.java
- src/main/resources/mappings/coupon-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myCoupon.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myLevel.jsp
쿠폰 중복지급 확인, 쿠폰함에 사용 가능 쿠폰 불러오기 구현 (쿠폰 선물하기 구현중)
> 쿠폰 중복지급 확인, 쿠폰함에 사용 가능 쿠폰 불러오기 구현 (쿠폰 선물하기 구현중)

- src/main/java/com/damino/web/admin/member/login/AdminMemberDAO.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginController.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginDAO.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginVO.java
- src/main/java/com/damino/web/admin/member/login/impl/AdminMemberLoginDAOImpl.java
- src/main/java/com/damino/web/admin/member/login/impl/AdminMemberLoginServiceImpl.java
- src/main/resources/mappings/adminmember-login-mapping.xml
- src/main/resources/mappings/adminmember-mapping.xml
- src/main/resources/mybatis-config.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/members/member/login.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/members/member/regForm.jsp
> 홈페이지관리자 로그인기능

- src/main/resources/mybatis-config.xml
<mapper resource="mappings/goods-mapping.xml"/>
-- 주석해제 후 사용해주세요 --
> maybits-config

- src/main/java/com/damino/web/user/coupon/CouponController.java
- src/main/java/com/damino/web/user/coupon/CouponDAO.java
- src/main/java/com/damino/web/user/coupon/CouponService.java
- src/main/java/com/damino/web/user/coupon/impl/CouponDAOImpl.java
- src/main/java/com/damino/web/user/coupon/impl/CouponServiceImpl.java
- src/main/resources/mappings/coupon-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myCoupon.jsp
쿠폰 선물하기 기능 추가 (쿠폰 테이블 update, LMS 문자 발송 기능)
> 쿠폰 선물하기 기능 추가 (쿠폰 테이블 update, LMS 문자 발송 기능)

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/goods/GoodsDrinkEtcVO.java
- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/GoodsPizzaVO.java
- src/main/java/com/damino/web/user/goods/GoodsSideVO.java
- src/main/java/com/damino/web/user/goods/GoodsToppingVO.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
1. 컨트롤러 - goodslist.do 주석처리(별도의 컨트롤러에서 구현 에정) 
2. 상품(피자, 사이드디쉬 등) 목록 불러오기 위한 클래스 파일 추가
> 상품(피자, 사이드디쉬 등) 목록 불러오기 위한 클래스 파일 추가 외 1건

- src/main/resources/mybatis-config.xml
> mybatis-config 주석해제

- src/main/java/com/damino/web/admin/board/BoardController.java
- src/main/java/com/damino/web/admin/terms/TermsController.java
- src/main/java/com/damino/web/admin/terms/TermsDAO.java
- src/main/java/com/damino/web/admin/terms/TermsService.java
- src/main/java/com/damino/web/admin/terms/TermsVO.java
- src/main/java/com/damino/web/admin/terms/impl/TermsDAOImpl.java
- src/main/java/com/damino/web/admin/terms/impl/TermsServiceImpl.java
- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/resources/mappings/terms-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/board/boardView.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/terms/terms_insert.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/terms/terms_list.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/terms/terms_view.jsp
홈페이지 관리자 약관 CRUD 추가
input type=date   insert는 되는데 update 안됨
> 홈페이지 관리자 약관 CRUD 추가

- src/main/java/com/damino/web/user/coupon/CouponController.java
- src/main/java/com/damino/web/user/coupon/CouponDAO.java
- src/main/java/com/damino/web/user/coupon/CouponService.java
- src/main/java/com/damino/web/user/coupon/impl/CouponDAOImpl.java
- src/main/java/com/damino/web/user/coupon/impl/CouponServiceImpl.java
- src/main/resources/mappings/coupon-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/ecoupon/ecouponInput.jsp
> e-coupon 선물받은 쿠폰 등록 기능 추가

- src/main/java/com/damino/web/user/login/LoginController.java
- src/main/java/com/damino/web/user/userinfo/UserInfoController.java
- src/main/java/com/damino/web/user/userinfo/UserInfoDAO.java
- src/main/java/com/damino/web/user/userinfo/UserInfoService.java
- src/main/java/com/damino/web/user/userinfo/UserInfoVO.java
- src/main/java/com/damino/web/user/userinfo/impl/UserInfoDAOImpl.java
- src/main/java/com/damino/web/user/userinfo/impl/UserInfoServiceImpl.java
- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/change_info.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
> 사용자 회원가입 수정 / 회원정보변경 진행중

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/coupon/CouponController.java
- src/main/webapp/WEB-INF/views/daminoUserView/ecoupon/ecouponInput.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/ecoupon/ecouponResult.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myLevel.jsp
뷰테스트컨트롤러 수정, 쿠폰 등록 성공시 결과 페이지로 이동 추가
> 뷰테스트컨트롤러 수정, 쿠폰 등록 성공시 결과 페이지로 이동 추가

- src/main/java/com/damino/web/admin/menu/MenuController.java
- src/main/java/com/damino/web/admin/menu/PizzaVO.java
- src/main/resources/mappings/menu-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/insertMenu_pizza.jsp
PizzaVO 멤버 수정, menu-mapping.xml 피자 등록 수정, insertMenu_pizza.jsp 폼 수정
> PizzaVO 멤버 수정, menu-mapping.xml 피자 등록 수정, insertMenu_pizza.jsp 폼 수정

- src/main/java/com/damino/web/admin/menu/MenuController.java
- src/main/webapp/WEB-INF/views/daminoAdminView/menu/menuList.jsp
menuList.jsp 수정 / MenuController 피자 등록 후 list로 redirect
> menuList.jsp 수정 / MenuController 피자 등록 후 list로 redirect

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/login/LoginController.java
- src/main/java/com/damino/web/user/userinfo/UserInfoController.java
- src/main/java/com/damino/web/user/userinfo/UserInfoDAO.java
- src/main/java/com/damino/web/user/userinfo/UserInfoService.java
- src/main/java/com/damino/web/user/userinfo/impl/UserInfoDAOImpl.java
- src/main/java/com/damino/web/user/userinfo/impl/UserInfoServiceImpl.java
- src/main/resources/mappings/usermember-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myUserInfoConfirm.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/change_info.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/userinfo/regForm.jsp
- src/main/webapp/resources/js/user/member.js
> 회원가입 / 회원정보 수정 끝

- src/main/webapp/WEB-INF/views/daminoUserView/goods/drink_list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/side_list.jsp
> 각 카테고리 선택시 현재 선택한 메뉴 강조 표시 적용

- src/main/webapp/WEB-INF/views/daminoUserView/branch.jsp
> branch.do 지도추가

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/resources/applicationContext.xml
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
1. 파일 업로드 최대 용량 10만 -> 500만 변경
2. 이미지 절대경로 jsp에 추가(이미지 로드 여부 확인 필요)
> 파일 업로드 최대 용량 10만 -> 500만 변경 외 1건

- src/main/webapp/WEB-INF/views/daminoUserView/branch.jsp
- src/main/webapp/resources/js/user/map.js
> branch.do 의 자바스크립트 map.js로 옮김

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/webapp/WEB-INF/views/daminoUserView/goods/drink_list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/side_list.jsp
사용자페이지 - 메뉴 이미지 불러오기 및 이미지 정렬 완료
> 사용자페이지 - 메뉴 이미지 불러오기 및 이미지 정렬 완료

- src/main/java/com/damino/web/admin/banner/BannerController.java
- src/main/java/com/damino/web/admin/banner/BannerDAO.java
- src/main/java/com/damino/web/admin/banner/BannerService.java
- src/main/java/com/damino/web/admin/banner/BannerVO.java
- src/main/java/com/damino/web/admin/banner/Impl/BannerDAOImpl.java
- src/main/java/com/damino/web/admin/banner/Impl/BannerServiceImpl.java
미구현
impl(프로그램 실행을 위해 현재 주석상태)
controller
mapping
> banner crud     --1차 세이브-- 

- src/main/java/com/damino/web/test/ViewTestController.java
> 제품 상세보기 화면 경로 이동

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
1. detail_goods.jsp 제품 상세보기 페이지 - 사용자 선택 제품 정보 불러오기 구현(제품명, 제품이미지)
2. list.jsp 주석 내용 삭제
> 제품 상세보기 페이지 - 사용자 선택 제품 정보 불러오기 구현(제품명, 제품이미지) 외 1건

- pom.xml
- src/main/java/com/damino/web/user/coupon/CouponController.java
- src/main/java/com/damino/web/user/coupon/CouponDAO.java
- src/main/java/com/damino/web/user/coupon/CouponService.java
- src/main/java/com/damino/web/user/coupon/impl/CouponDAOImpl.java
- src/main/java/com/damino/web/user/coupon/impl/CouponServiceImpl.java
- src/main/java/com/damino/web/user/login/LoginController.java
- src/main/resources/applicationContext.xml
- src/main/resources/mappings/coupon-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/ecoupon/ecouponInput.jsp
매일 0시 0분 0초마다 유효기간 만료 쿠폰 사용불가처리 기능 구현 (quartz, quatz-jobs 의존성 추가)
> 매일 0시 0분 0초마다 유효기간 만료 쿠폰 사용불가처리 기능 구현 (quartz, quatz-jobs 의존성 추가)

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
제품 상세보기 - 제품 도우정보 db에서 불러오기 및 라디오버튼 구현(현재 하나만 선택됨)
> 제품 상세보기 - 제품 도우정보 db에서 불러오기 및 라디오버튼 구현(현재 하나만 선택됨)

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/main/webapp/resources/js/user/ui.js
제품 상세화면 - 피자와 일치하는 도우 라디오박스로 구현 및 도우별 추가요금 지정
> 제품 상세화면 - 피자와 일치하는 도우 라디오박스로 구현 및 도우별 추가요금 지정

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
1. 제품 상세화면 - 하단 제품명 추가(가격 변경 필요)
2. 제품 목록 fmt 태그 적용(천단위 쉼표)
> 제품 상세화면 - 하단 제품명 추가(가격 변경 필요) 외 1건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/resources/mappings/market_admin_member-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
제품 상세 화면 - 토핑 타입(메인, 치즈, 애프터)별 조회 기능 추가
> 제품 상세 화면 - 토핑 타입(메인, 치즈, 애프터)별 조회 기능 추가

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
제품 세부사항 - 토핑 종류별 최대 수량 5개로 세팅(토핑 전체 5개로 한정할 예정)
> 제품 세부사항 - 토핑 종류별 최대 수량 5개로 세팅(토핑 전체 5개로 한정할 예정)

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
전체 카운트, 개별 카운트 각 최대수량 5개로 지정중(미구현)
> 전체 카운트, 개별 카운트 각 최대수량 5개로 지정중(미구현)

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
> 전체 토핑수 카운트중

- src/main/java/com/damino/web/user/map/MapController.java
- src/main/java/com/damino/web/user/map/MapDAO.java
- src/main/java/com/damino/web/user/map/MapService.java
- src/main/java/com/damino/web/user/map/impl/MapDAOImpl.java
- src/main/java/com/damino/web/user/map/impl/MapServiceImpl.java
- src/main/resources/mappings/map-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/branch.jsp
- src/main/webapp/resources/js/user/map.js
> 지역검색 / 매장명검색 하면 리스트에 표시

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
- src/main/webapp/resources/js/user/ui.js
제품 상세화면
1. 제품 확대 이미지 팝업 기능 구현
2. 사이즈 선택 라디오버튼 기능 구현
> 제품 상세화면 - 제품 확대 이미지 팝업 기능 구현 외 1건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
제품 상세화면 - 사이드디시 > 일반만 활성화 및 선택 최대수량 9개로 지정
> 제품 상세화면 - 사이드디시 > 일반만 활성화 및 선택 최대수량 9개로 지정

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
제품 상세화면
1. 피자 최대수량 9개로 지정
2. 음료 최대수량 피자와 2:1 비율로 지정
> 제품 상세화면 - 피자 최대수량 9개로 지정 외 1건

- src/main/java/com/damino/web/user/map/MapController.java
- src/main/webapp/WEB-INF/views/daminoUserView/branch2.jsp
- src/main/webapp/resources/js/user/map.js
> 지도에 마커찍는거 빼고 끝

- src/main/java/com/damino/web/user/quickorder/QuickOrderController.java
- src/main/java/com/damino/web/user/quickorder/QuickOrderDAO.java
- src/main/java/com/damino/web/user/quickorder/QuickOrderService.java
- src/main/java/com/damino/web/user/quickorder/impl/QuickOrderDAOImpl.java
- src/main/java/com/damino/web/user/quickorder/impl/QuickOrderServiceImpl.java
- src/main/resources/mappings/quickorder-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/quickOrder_defaultSetting.jsp
퀵오더 설정페이지 선택 제품 추가 / 총 가격 계산 / 특정 row 삭제 구현 완료
> 퀵오더 설정페이지 선택 제품 추가 / 총 가격 계산 / 특정 row 삭제 구현 완료

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/test.jsp
메뉴 상세화면 - 토핑, 사이드디시, 음료, 피자 수량 제한 설정 완료. (도우 진행중)
> 메뉴 상세화면 - 토핑, 사이드디시, 음료, 피자 수량 제한 설정 완료. (도우 진행중)

- src/main/webapp/WEB-INF/views/daminoUserView/branch.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/branch2.jsp
- src/main/webapp/resources/js/user/map.js
> 지역검색 / 매장명 검색 지도표시

- src/main/java/com/damino/web/user/quickorder/QuickOrderController.java
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/detailAddr.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/quickOrder_defaultSetting.jsp
퀵오더 설정 - 주소검색 API 활용&상세주소 입력창 추가하여 배달 주소 목록에 추가기능 구현
> 퀵오더 설정 - 주소검색 API 활용&상세주소 입력창 추가하여 배달 주소 목록에 추가기능 구현

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
제품 상세정보
1. 토핑, 음료 선택정보 하단 박스에 바인딩 처리
2. 사이드디시 plus 카운트 오류 수정 및 선택한 음료정보 바인딩 완료
3. 제품 상세화면 - 도우 선택된 라디오박스 값 바인딩 (진행중)
> 제품 상세정보 - 토핑, 음료 선택정보 하단 박스에 바인딩 처리 외 2건

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
제품 상세화면 - 총 금액 제외한 사용자 선택 정보 반영 완료
ㅇ피자이름
ㅇ피자수량
ㅇ도우이름
ㅇ도우가격
ㅇ사이드디시 이름
ㅇ사이드디시 가격
ㅇ음료 이름
ㅇ음료 가격
> 제품 상세화면 - 총 금액 제외한 사용자 선택 정보 반영 완료

- src/main/webapp/WEB-INF/views/daminoUserView/branch.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/branch2.jsp
> 상단 로그인상태 추가

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
제품 상세화면 - 피자, 도우, 사이드디시, 음료&기타 정보 및 총 금액 반영 완료
> 제품 상세화면 - 피자, 도우, 사이드디시, 음료&기타 정보 및 총 금액 반영 완료

- src/main/java/com/damino/web/test/space/TestSpaceController.java
- src/main/java/com/damino/web/test/space/TestSpaceDAO.java
- src/main/java/com/damino/web/test/space/TestSpaceService.java
- src/main/java/com/damino/web/test/space/impl/TestSpaceDAOImpl.java
- src/main/java/com/damino/web/test/space/impl/TestSpaceServiceImpl.java
- src/main/resources/mappings/test-mapping.xml
- src/main/resources/mybatis-config.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/testSpace.jsp
> DB 와차트 연동 성공

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods_side.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/side_list.jsp
사이드디시 목록 화면 작업 및 사이드디시 상세 화면 작업 진행중
> 사이드디시 목록 화면 작업 및 사이드디시 상세 화면 작업 진행중

- src/main/java/com/damino/web/user/quickorder/QuickOrderAddressVO.java
- src/main/java/com/damino/web/user/quickorder/QuickOrderController.java
- src/main/java/com/damino/web/user/quickorder/QuickOrderDAO.java
- src/main/java/com/damino/web/user/quickorder/QuickOrderGoodsVO.java
- src/main/java/com/damino/web/user/quickorder/QuickOrderService.java
- src/main/java/com/damino/web/user/quickorder/QuickOrderVO.java
- src/main/java/com/damino/web/user/quickorder/impl/QuickOrderDAOImpl.java
- src/main/java/com/damino/web/user/quickorder/impl/QuickOrderServiceImpl.java
- src/main/resources/mappings/quickorder-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/detailAddr.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/quickOrder.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/quickOrder_defaultSetting.jsp
퀵오더 설정페이지 메뉴 추가 삭제, 주소 추가 삭제 DB연동 완료, 총가격 계산 완료
> 퀵오더 설정페이지 메뉴 추가 삭제, 주소 추가 삭제 DB연동 완료, 총가격 계산 완료

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods_side.jsp
제품 상세화면 - 사이드디시 화면(사이드디시, 음료) 수량 카운트 및 금액 반영 완료
> 제품 상세화면 - 사이드디시 화면(사이드디시, 음료) 수량 카운트 및 금액 반영 완료

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods_side.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/drink_list.jsp
1. 사이드 상세 화면 - 가격 fmt 태그 적용
2. 피자 상세 화면
- 도우 라디오버튼 디폴트값 0번째 선택 및 총금액 합산 적용
- 주문하기 관련 POST 방식 진행중
3. 음료 목록 화면 - 수량 카운트 및 주문버튼 알림기능 적용
> 도우 라디오버튼 디폴트값 0번째 선택 및 총금액 합산 적용 외 3건

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/quickorder/QuickOrderController.java
- src/main/java/com/damino/web/user/quickorder/QuickOrderDAO.java
- src/main/resources/mappings/quickorder-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/quickOrder.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/quickOrder_defaultSetting.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/quickOrder_payment.jsp
> 나의 퀵오더 불러오기, 퀵오더 결제하기 페이지 진행중

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/basket/detailAddr.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
1. detail_goods.jsp - 상세주소, 지점명 hidden 으로 받아오기 완료
2. detail_goods.jsp - 주소 추가 관련 다음 api 사용
3. ViewTestController - 기존 장바구니 경로 주석처리
> detail_goods.jsp - 상세주소, 지점명 hidden 으로 받아오기 완료 외 2건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/GoodsToppingVO.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/basket/detailAddr.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
장바구니
1. 사용자 선택정보(피자 이름, 가격, 사이즈) 반영 완료
2. 사용자 선택정보(배열 정보)에 해당하는 DB 정보 진행중(미구현)
> 장바구니 - 사용자 선택정보(피자 이름, 가격, 사이즈) 반영 완료 외 1건

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/orderlist/MyOrderListController.java
> orderlist 에러 수정

- src/main/java/com/damino/web/admin/salesstatus/SalesStatusController.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusDAO.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusService.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusDAOImpl.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusServiceImpl.java
- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/resources/mappings/salesstauts-mapping.xml
- src/main/resources/mybatis-config.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/store_sales/salesStatus.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/testPrice.jsp
남녀성비 차트 DB(usermember) 연동
testPrice.admdo
아임포트 api로 실제로 결제까지 가능
결제정보조회 고민중..
> salesStatus

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
> 장바구니 - 토핑 이름, 가격 반영 완료

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
1. 제품 상세페이지 - 주문하기버튼 미클릭시 페이지이동 오류 수정
2. 사용자 선택(피자, 사이드, 음료) 정보 insert 완료
> 제품 상세페이지 - 주문하기버튼 미클릭시 페이지이동 오류 수정 외 1건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
1. 장바구니 조회 기능 구현
2. 피자이미지 추가 로딩 완료
> 장바구니 조회 기능 구현 외 1건

- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
장바구니
1. 사이드, 음료정보 불러오기 완료(2개 이상일 때 li 영역 분리 필요)
2. 피자, 사이드, 음료 합계 금액 반영 완료
3. 사용자가 선택한 제품 수량정보 불러오기 완료
> 사이드, 음료정보 불러오기 완료(2개 이상일 때 li 영역 분리 필요) 외 2건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/main.jsp
장바구니
1. 특정 DB의 컬럼 데이터 일부 변경 작업 진행중(토핑삭제 관련)
2. main.jsp 장바구니 경로 추가
> 특정 DB의 컬럼 데이터 일부 변경 작업 진행중(토핑삭제 관련) 외 1건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
> 메인 장바구니 경로 설정 관련 컨트롤러 수정

- src/main/webapp/WEB-INF/views/daminoManagerView/members/main.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/order/storeOrderList.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/order/storeOrderSearch.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/statistics/statistics_list.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/store/storeManagerInfo.jsp
> 매장관리자 페이지 네비게이션바 수정

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
장바구니
1. 피자, 사이드 삭제 기능 구현(update 쿼리) - 토핑, 음료 미구현
2. 합계금액 계산 완료
3. 피자, 사이드디시, 음료 이름이 모두 없을경우 html 추가
> 피자, 사이드 삭제 기능 구현(update 쿼리) - 토핑, 음료 미구현 외 2건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/drink_list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/side_list.jsp
1. 장바구니 음료 삭제기능 구현
2. list, side_list, drink_list.jsp 회원 로그인시 화면상단 회원 이름 정보 셋팅
> 장바구니 음료 삭제기능 구현 외 1건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
장바구니 - DB 구분정보 가져오기 완료
제품 상세화면 - 선택하지 않은 메뉴 정보 확인용 로직 수정
> 장바구니 - DB 구분정보 가져오기 완료 외 1건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
> 토핑 가격 합산 진행중

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods_side.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
1. 사이드 상세화면 - 천단위 구분 쉼표 추가, 가격 합산 수정
2. 컨트롤러 - 피자값 없을 때 vo셋팅 하지 않게 조정
3. 클래식피자 경로 변경
> 사이드 상세화면 - 천단위 구분 쉼표 추가, 가격 합산 수정 외 2건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods_side.jsp
제품 상세화면 - 장바구니 추가한 목록 없을 때 gubunDB 0으로 셋팅
> 제품 상세화면 - 장바구니 추가한 목록 없을 때 gubunDB 0으로 셋팅

- src/main/java/com/damino/web/user/order/OrderController.java
- src/main/java/com/damino/web/user/order/OrderDAO.java
- src/main/java/com/damino/web/user/order/OrderService.java
- src/main/java/com/damino/web/user/order/StoreAddressVO.java
- src/main/java/com/damino/web/user/order/impl/OrderDAOImpl.java
- src/main/java/com/damino/web/user/order/impl/OrderServiceImpl.java
- src/main/resources/mappings/order-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/branch2.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/orderGubun.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/detailAddr.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/storeAddr.jsp
> 포장매장 등록 진행중

- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
장바구니 - 토핑, 피자, 음료, 사이드디시 합계 금액 반영 완료
> 장바구니 - 토핑, 피자, 음료, 사이드디시 합계 금액 반영 완료

- src/main/java/com/damino/web/user/order/OrderController.java
- src/main/java/com/damino/web/user/order/OrderDAO.java
- src/main/java/com/damino/web/user/order/OrderService.java
- src/main/java/com/damino/web/user/order/impl/OrderDAOImpl.java
- src/main/java/com/damino/web/user/order/impl/OrderServiceImpl.java
- src/main/resources/mappings/order-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/branch2.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/orderGubun.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/quickorder/storeAddr.jsp
> 포장매장부분 완료 지도검색페이지와 연결 완료

- src/main/webapp/WEB-INF/views/daminoUserView/branch2.jsp
> 매장검색 방문포장 링크 세션체크 추가

- src/main/java/com/damino/web/admin/board/BoardDAO.java
- src/main/java/com/damino/web/admin/board/BoardService.java
- src/main/java/com/damino/web/admin/board/impl/BoardDAOImpl.java
- src/main/java/com/damino/web/admin/board/impl/BoardServiceImpl.java
- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/resources/mappings/board-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/main.jsp
<viewcontroller 건든분만 해당>
<board-mapping, board 관련분 해당>
홈페이지관리자 admin.admdo
공지시항 링크 및 이동 연결
> 홈페이지관리자 공지사항 링크

- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
장바구니 - 금액 합산 완료, 시퀀스순으로 각 상품 정렬
> 장바구니 - 금액 합산 완료, 시퀀스순으로 각 상품 정렬

- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
> 장바구니 - 피자, 사이드디시, 음료 카운트 제한

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/UserBasketVO.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
장바구니 - 제품 수량 증감에 따른 금액 반영 (토핑 있는 피자의 경우 미구현)
> 장바구니 - 제품 수량 증감에 따른 금액 반영 (토핑 있는 피자의 경우 미구현)

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
> 장바구니 - 전체삭제 기능 구현

- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
> 장바구니 - 토핑이 1개일 때 피자 합산 금액 수정

- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
장바구니 - 토핑 개수가 피자 개수보다 작을 경우 금액 반영수정
> 장바구니 - 토핑 개수가 피자 개수보다 작을 경우 금액 반영수정

- src/main/java/com/damino/web/admin/salesstatus/SalesStatusController.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusDAO.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusService.java
- src/main/java/com/damino/web/admin/salesstatus/SalesVO.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusDAOImpl.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusServiceImpl.java
- src/main/resources/mappings/salesstauts-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/store_sales/salesStatus.jsp
- src/main/webapp/resources/js/admin/chart-area-month.js
salesStatus.admdo
order_list 테이블 월별 데이터로 라인차트 완성
> order_list 테이블 데이터로 라인차트

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/java/com/damino/web/user/order/OrderController.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
장바구니 - 피자, 사이드디시, 음료 total 수량 체크 및 초기화 기능 구현
주문하기
1. 사용자 쿠폰정보 불러오기 기능 진행중
2. 피자, 사이드디시 메뉴없이 음료만 있을 때 주문 안되게 구현할 예정 / 사이드디시 + 음료 최소 주문금액 설정 예정
> 장바구니 - 피자, 사이드디시, 음료 total 수량 체크 및 초기화 기능 구현 외 2건

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/order/OrderController.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
1. 장바구니 - 수량체크 및 초기화 기능 '주문하기' 버튼 눌렀을 때 작동으로 변경(주문하기 누르기전엔 수량 제한없이 DB에 반영됨)
2. 쿠폰 발급 및 orderPage.do 작업 진행중
> 장바구니 - 수량체크 및 초기화 기능 '주문하기' 버튼 눌렀을 때 작동으로 변경 외 1건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/order/OrderController.java
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page.jsp
장바구니 - 주문페이지 이동전 사용자 쿠폰 발급 여부 체크후 추가
주문페이지
1. 주문자정보 셋팅 기능 추가(현 : 세션에 저장된 사용자 정보) -> 세션에 저장해둔 정보가 금방 없어져서 DB 조회 불러오는것 고려중
2. 장바구니 리스트 불러오기 구현 및 카운트 체크
> 장바구니 - 주문페이지 이동전 사용자 쿠폰 발급 여부 체크후 추가 외 2건

- src/main/java/com/damino/web/user/order/DeliveryAddressVO.java
- src/main/java/com/damino/web/user/order/OrderController.java
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page.jsp
1. 컨트롤러 - 세션시간 연장(세션의 매장명이 없는 경우 DB에서 조회하도록 설정)
2. 할인쿠폰 반영, 매장시간 반영
> 컨트롤러 - 세션시간 연장(세션의 매장명이 없는 경우 DB에서 조회하도록 설정) 외 2건

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/UserOrderVO.java
- src/main/java/com/damino/web/user/order/OrderController.java
- src/main/java/com/damino/web/user/order/OrderDAO.java
- src/main/java/com/damino/web/user/order/OrderService.java
- src/main/java/com/damino/web/user/order/impl/OrderDAOImpl.java
- src/main/java/com/damino/web/user/order/impl/OrderServiceImpl.java
- src/main/resources/mappings/order-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page.jsp
주문내역 DB insert 완료 및 주문완료 페이지 연결
(세션 정보가 만료되어 없는 경우 null로 들어와서 관련하여 확인중)
> 주문내역 DB insert 완료 및 주문완료 페이지 연결

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/web.xml
1. 전체페이지 세션 만료시간 60분으로 설정
2. 장바구니 클릭시 세션의 정보가 없을 때 DB에 저장된 주소지 세팅
> 전체페이지 세션 만료시간 60분으로 설정 외 1건

- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/order/OrderController.java
- src/main/java/com/damino/web/user/orderlist/MyOrderListController.java
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myOrderList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_orderDone.jsp
1. 주문완료 페이지(배달유형, 매장명, 매장전화번호) 세팅 완료
2. mypage - myorderlist 세션 사용자정보 세팅 및 세션정보 없을시 로그인 화면 이동
3. (진행해야 할 것) seq순으로 내림차순 정렬로 mapping 되어있으나 주문일시가 나열되어있지 않음. 확인 예정. 페이징 처리도 추가로 진행 예정
> 주문완료 페이지(배달유형, 매장명, 매장전화번호) 세팅 완료 외 2건

- src/main/java/com/damino/web/admin/salesstatus/SalesStatusController.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusDAO.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusService.java
- src/main/java/com/damino/web/admin/salesstatus/SalesVO.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusDAOImpl.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusServiceImpl.java
- src/main/resources/mappings/salesstauts-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/store_sales/salesStatus.jsp
- src/main/webapp/resources/js/admin/chart-area-search.js
- src/main/webapp/resources/js/admin/chart-area-year.js
매출 상세 검색 추가
날짜 선택후 검색시 해당 날짜 판매내역 표시
차트로 반영
> 매출 상세검색 추가

- src/main/java/com/damino/web/user/board/QnaBoardController.java
- src/main/java/com/damino/web/user/board/QnaBoardDAO.java
- src/main/java/com/damino/web/user/board/QnaBoardService.java
- src/main/java/com/damino/web/user/board/impl/QnaBoardDAOImpl.java
- src/main/java/com/damino/web/user/board/impl/QnaBoardServiceImpl.java
- src/main/resources/mappings/board-mapping.xml
1:1 문의사항 사용자 게시글 카운트 쿼리 수정 및 어드민 전체 게시글 카운트 쿼리 추가
> 1:1 문의사항 사용자 게시글 카운트 쿼리 수정 및 어드민 전체 게시글 카운트 쿼리 추가

- src/main/java/com/damino/web/user/login/LoginController.java
- src/main/java/com/damino/web/user/order/OrderController.java
- src/main/java/com/damino/web/user/orderlist/MyOrderListController.java
- src/main/java/com/damino/web/user/orderlist/MyOrderListDAO.java
- src/main/java/com/damino/web/user/orderlist/MyOrderListService.java
- src/main/java/com/damino/web/user/orderlist/impl/MyOrderListDAOImpl.java
- src/main/java/com/damino/web/user/orderlist/impl/MyOrderListServiceImpl.java
- src/main/resources/mappings/orderlist-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myOrderList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myQuestionList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page.jsp
1. 주문페이지 - 기존 추가한 세션정보를 못받아 주소, 매장 정보 등 추가
2. 주문내역 - 페이징처리 완료(10개 단위)
> 주문페이지 - 기존 추가한 세션정보를 못받아 주소, 매장 정보 등 추가 외 1건

- src/main/java/com/damino/web/admin/market/member/regist/MarketAdminMemberVO.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginController.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginDAO.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginService.java
- src/main/java/com/damino/web/admin/member/login/impl/AdminMemberLoginDAOImpl.java
- src/main/java/com/damino/web/admin/member/login/impl/AdminMemberLoginServiceImpl.java
- src/main/java/com/damino/web/admin/member/regist/AdminMemberController.java
- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/resources/mappings/adminmember-login-mapping.xml
- src/main/resources/mappings/adminmember-mapping.xml
- src/main/resources/mappings/market_admin_member-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/members/market/marketList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myOrderList.jsp
홈페이지 관리자 - 매장관리자 점포 승인 관련 등록된 관리자 명단 불러오기 구현
> 홈페이지 관리자 - 매장관리자 점포 승인 관련 등록된 관리자 명단 불러오기 구현

- src/main/java/com/damino/web/admin/salesstatus/SalesStatusDAO.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusService.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusDAOImpl.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusServiceImpl.java
- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/resources/mappings/salesstauts-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/main.jsp
- src/main/webapp/resources/js/admin/chart-bar-day.js
viewtestcontroller와 salesstatus 해당
>  main페이지 일일건수 차트  -수정중_

- src/main/java/com/damino/web/admin/market/member/login/MarketAdminLoginController.java
- src/main/java/com/damino/web/admin/market/member/login/MarketAdminVO.java
- src/main/java/com/damino/web/admin/market/member/regist/MarketAdminMemberVO.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginController.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginDAO.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginService.java
- src/main/java/com/damino/web/admin/member/login/impl/AdminMemberLoginDAOImpl.java
- src/main/java/com/damino/web/admin/member/login/impl/AdminMemberLoginServiceImpl.java
- src/main/resources/mappings/adminmember-login-mapping.xml
- src/main/resources/mappings/market_admin_member-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/members/market/marketList.jsp
1. 매장관리자페이지 - 로그인시 홈페이지관리자에게 승인 받아야 로그인 가능으로 변경
2. 홈페이지관리자페이지 - 매장관리자 삭제 및 승인기능 추가
> 매장관리자페이지 - 로그인시 홈페이지관리자에게 승인 받아야 로그인 가능으로 변경 외 1건

- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginController.java
- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/GoodsListDAO.java
- src/main/java/com/damino/web/user/goods/GoodsListService.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListDAOImpl.java
- src/main/java/com/damino/web/user/goods/impl/GoodsListServiceImpl.java
- src/main/resources/mappings/goods-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/members/market/marketList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods_side.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/side_list.jsp
1. 홈페이지 관리자페이지 ajax 오류 수정
2. 사이드메뉴 상세화면에서 주문까지 연결 완료. 주문 기능 확인 완료
> 홈페이지 관리자페이지 ajax 오류 수정 외 1건

- src/main/java/com/damino/web/admin/salesstatus/SalesStatusController.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusDAO.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusService.java
- src/main/java/com/damino/web/admin/salesstatus/SalesVO.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusDAOImpl.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusServiceImpl.java
- src/main/resources/mappings/salesstauts-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/store_sales/salesStatus.jsp
- src/main/webapp/resources/js/admin/chart-area-search.js
- src/main/webapp/resources/js/admin/chart-bar-search.js
> 홈페이지 관리자 매출 통계 상세검색 완료

- src/main/java/com/damino/web/admin/board/impl/BoardServiceImpl.java
- src/main/java/com/damino/web/admin/faq/FaqDAO.java
- src/main/java/com/damino/web/admin/faq/FaqService.java
- src/main/java/com/damino/web/admin/faq/impl/FaqDAOImpl.java
- src/main/java/com/damino/web/admin/faq/impl/FaqServiceImpl.java
- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/resources/mappings/faq-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/main.jsp
주문내역 >>> Q&A 로 바꿈 표시
faq , viewcontroller 해당
> 홈페이지관리자 >>

- src/main/java/com/damino/web/admin/market/member/login/MarketAdminDAO.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginController.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginDAO.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginService.java
- src/main/java/com/damino/web/admin/member/login/impl/AdminMemberLoginDAOImpl.java
- src/main/java/com/damino/web/admin/member/login/impl/AdminMemberLoginServiceImpl.java
- src/main/resources/mappings/adminmember-login-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/members/market/marketEdit.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/members/market/marketList.jsp
홈페이지관리자페이지 - 매장관리자 비밀번호 변경 기능 추가 및 변경된 비밀번호 암호화 완료
> 홈페이지관리자페이지 - 매장관리자 비밀번호 변경 기능 추가 및 변경된 비밀번호 암호화 완료

- src/main/java/com/damino/web/admin/market/member/login/MarketAdminLoginController.java
- src/main/webapp/WEB-INF/views/daminoAdminView/members/market/marketEdit.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/members/market/marketList.jsp
> 매장관리자페이지 - 통계 관련 vo 세팅

- src/main/java/com/damino/web/admin/market/member/login/MarketAdminLoginController.java
- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/webapp/WEB-INF/views/daminoManagerView/members/managerLogin.jsp
null 포인터 오류 수정 및 매장관리자페이지 오류 수정
> null 포인터 오류 수정 및 매장관리자페이지 오류 수정

- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginController.java
- src/main/java/com/damino/web/user/login/LoginController.java
- src/main/webapp/WEB-INF/views/daminoAdminView/members/member/login.jsp
> 로그인 controller시

- src/main/java/com/damino/web/admin/market/member/login/MarketAdminLoginController.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusDAO.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusService.java
- src/main/java/com/damino/web/admin/salesstatus/SalesVO.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusDAOImpl.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusServiceImpl.java
- src/main/resources/mappings/salesstauts-mapping.xml
- src/main/webapp/WEB-INF/views/daminoManagerView/members/main.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/members/managerLogin.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/order/storeOrderList.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/order/storeOrderSearch.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/statistics/statistics_list.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/store/storeManagerInfo.jsp
- src/main/webapp/resources/js/admin/chart-area-month-store.js
- src/main/webapp/resources/js/admin/chart-bar-month-store.js
- src/main/webapp/resources/js/admin/chart-bar-year-store2.js
> 매장관리자 대시보드 완료

- pom.xml
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusController.java
- src/main/java/com/damino/web/test/ExcelDownloadView.java
- src/main/resources/applicationContext.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/store_sales/salesStatus.jsp
홈페이지관리자페이지 - PDF 다운로드 기능 완료 / EXCEL 다운로드 진행중
> 홈페이지관리자페이지 - PDF 다운로드 기능 완료 / EXCEL 다운로드 진행중

- src/main/resources/applicationContext.xml
applicationContext.xml  2줄 주석처리
> applicationContext.xml  2줄 주석처리

- src/main/webapp/WEB-INF/views/daminoAdminView/store_sales/salesStatus.jsp
검색 기능 관련 PDF 버튼 수정 및 PDF 사이즈 조정
> 검색 기능 관련 PDF 버튼 수정 및 PDF 사이즈 조정

- src/main/java/com/damino/web/admin/market/member/regist/MarketAdminRegistController.java
- src/main/java/com/damino/web/admin/market/orderlist/StoreOrderListController.java
- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/webapp/WEB-INF/views/daminoManagerView/order/storeOrderSearch.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/store/storeManagerInfo.jsp
매장관리자 주문검색 기능추가
viewtestcontroller 수정
> 매장관리자 주문검색 기능추가

- src/main/java/com/damino/web/admin/market/member/regist/MarketAdminMemberDAO.java
- src/main/java/com/damino/web/admin/market/member/regist/MarketAdminRegistController.java
- src/main/java/com/damino/web/admin/market/member/regist/MarketAdminRegistService.java
- src/main/java/com/damino/web/admin/market/member/regist/impl/MarketAdminMemberDAOImpl.java
- src/main/java/com/damino/web/admin/market/member/regist/impl/MarketAdminRegistServiceImpl.java
- src/main/resources/mappings/market_admin_member-mapping.xml
- src/main/webapp/WEB-INF/views/daminoManagerView/members/main.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/order/storeOrderList.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/order/storeOrderSearch.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/statistics/statistics_list.jsp
- src/main/webapp/WEB-INF/views/daminoManagerView/store/storeManagerInfo.jsp
> 관리자 설정 페이지

- src/main/webapp/WEB-INF/views/daminoUserView/order/orderStatus.jsp
금액 천단위 구분 쉼표 적용 및 주문내역 print 기능 적용
> 금액 천단위 구분 쉼표 적용 및 주문내역 print 기능 적용

- src/main/java/com/damino/web/user/goods/GoodsListController.java
- src/main/java/com/damino/web/user/goods/UserOrderVO.java
- src/main/java/com/damino/web/user/order/OrderController.java
- src/main/java/com/damino/web/user/orderlist/MyOrderListVO.java
- src/main/resources/mappings/order-mapping.xml
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page.jsp
detail.do 널포인터 에러 수정 및 할인금액 관련 vo, 컬럼 추가
> detail.do 널포인터 에러 수정 및 할인금액 관련 vo, 컬럼 추가

- src/main/java/com/damino/web/user/order/OrderController.java
- src/main/webapp/WEB-INF/views/daminoUserView/order/orderStatus.jsp
> 주문내역 - 할인전 금액, 할인금액 반영

- src/main/webapp/WEB-INF/views/daminoAdminView/store/storeView.jsp
> 홈페이지 관리자 수정

- src/main/java/com/damino/web/admin/banner/BannerController.java
- src/main/java/com/damino/web/admin/main/AdminMainController.java
- src/main/java/com/damino/web/admin/member/login/AdminMemberLoginController.java
- src/main/java/com/damino/web/admin/member/regist/AdminMemberController.java
- src/main/java/com/damino/web/test/ViewTestController.java
- src/main/java/com/damino/web/user/main/UserMainController.java
- src/main/webapp/WEB-INF/views/daminoAdminView/sites/banner/bannerBoardEdit.jsp
banneredit >> bannercontroller
login 관련 == admin memberlogincontroller
홈페이지관리자 비밀번호변경, 등록 페이지 >> regist/adminmeberController
main.admdo
admin/main/adminMainController
main.do
user/main/UserMainController
>  view테스트컨트롤 이사

- src/main/resources/mybatis-config.xml
test-mapping.xml 파일 없는 관계로 관련 내용 삭제
> test-mapping.xml 파일 없는 관계로 관련 내용 삭제

- src/main/webapp/WEB-INF/views/daminoAdminView/members/member/memberInfo.jsp
- src/main/webapp/WEB-INF/views/daminoAdminView/store/storeView.jsp
> 이메일 / sms발송 삭제

- src/main/java/com/damino/web/admin/salesstatus/SalesStatusController.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusDAO.java
- src/main/java/com/damino/web/admin/salesstatus/SalesStatusService.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusDAOImpl.java
- src/main/java/com/damino/web/admin/salesstatus/impl/SalesStatusServiceImpl.java
- src/main/resources/mappings/salesstauts-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/store_sales/salesStatus.jsp
홈페이지관리자페이지 - 배달 유형별 파이차트 구현
총 매출액 천단위 구분 쉼표 추가
> 홈페이지관리자페이지 - 배달 유형별 파이차트 구현 외 1건

- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page.jsp
> 주문페이지 - 쿠폰 사용 관련 에러 수정

- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods_side.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/drink_list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/goods/side_list.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page.jsp
> 제품 설명 팝업 위치 조정, 불필요 내용 삭제

- src/main/webapp/WEB-INF/views/daminoUserView/order/orderStatus.jsp
사용자 나의정보 주문내역 상세보기 페이지
orderStatus.jsp  수정
> 사용자 나의정보 주문내역 상세보기 페이지

- src/main/webapp/WEB-INF/views/daminoManagerView/order/storeOrderSearch.jsp
> storeOrderSearch.jsp 수정

- src/main/resources/mappings/orderlist-mapping.xml
- src/main/webapp/WEB-INF/views/daminoAdminView/members/market/marketList.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/basket/basket_detail.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/mypage/myQuestion_view.jsp
- src/main/webapp/WEB-INF/views/daminoUserView/order/order_page.jsp
1. 장바구니 - 장바구니 아이콘 빨간점 제거
2. 주문내역 - 제품 카운트 로직 수정
3. 1:1문의사항 - 목록버튼 기능 추가
> 주문내역 - 제품 카운트 로직 수정 외 2건

- src/daminoSequence.useq
- src/main/webapp/WEB-INF/views/daminoUserView/goods/detail_goods.jsp
- src/user.branch.useq
- src/user.coupon.useq
1. 시퀀스다이어그램 추가(사용자페이지 주문 프로세스, 매장검색, e쿠폰 등록)
2. 피자 상세페이지 - 인기순 항목 삭제(주석처리)
> 시퀀스다이어그램 추가(사용자페이지 주문 프로세스, 매장검색, e쿠폰 등록) 외 1건

- src/homepage-admin.menu.useq
- src/homepage-admin.statistic1.useq
- src/homepage-admin.statistic2.useq
- src/market-admin.statisticList1.useq
- src/market-admin.statisticList2.useq
홈페이지관리자
- 주문/매출관리 - 매출현황
- 메뉴관리 - 메뉴 등록
매장관리자
- 주문/매출관리 - 매출현황
> <시퀀스 다이어그램 추가>
